import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./_components/navbar";
// import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Bra Thobi's POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const currentPath = usePathname()
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-slate-400 to-gray-700 h-full ">
        {/* <NavBar/> */}
        {children}
      </body>
    </html>
  );
}
