# Generated by Django 5.0.6 on 2024-05-18 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_usermodel_updatedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('change', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usermodel')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['createdAt'],
            },
        ),
    ]
