# Generated by Django 5.0.6 on 2024-05-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('transactions', '0002_transacionmodel_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacionmodel',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productmodel'),
        ),
    ]
