# Generated by Django 5.0.6 on 2024-05-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('transactions', '0004_rename_transacionmodel_transactionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='products',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.productmodel'),
        ),
    ]
