# Generated by Django 5.0.6 on 2024-05-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transactionmodel_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'ordering': ['-createdAt']},
        ),
    ]
