# Generated by Django 5.0.6 on 2024-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
