# Generated by Django 5.0.6 on 2024-05-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_updatedat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-createdAt']},
        ),
    ]
